base/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import CourseResource, CategoryResource
from tastypie.api import Api

api = Api(api_name='v1')
course_resource = CourseResource()
category_resource = CategoryResource()
api.register(course_resource)
api.register(category_resource)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('api/', include(api.urls)),
]

shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'
urlpatterns = [
     path('', views.index, name='index'),
     path('<int:course_id>', views.single_course, name='single_course'),
]

api/models.py
from tastypie.resources import ModelResource
from tastypie.authentication import Authentication
from tastypie.authorization import Authorization  # Добавляем импорт
from shop.models import Category, Course
from .authentication import CustomApiKeyAuthentication

class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get']
        authentication = CustomApiKeyAuthentication()
        authorization = Authorization()  # Добавляем

class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allowed_methods = ['get', 'post', 'delete']
        authentication = CustomApiKeyAuthentication()
        authorization = Authorization()  # Исправляем

shop/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Course(models.Model):
    title = models.CharField(max_length=245)
    price = models.FloatField()
    student_qty = models.IntegerField()
    review_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title + ' ' + str(self.review_qty)

api/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from gc import get_objects

from django.http.response import Http404
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Course
# Create your views here.

def index(request):
    courses = Course.objects.all()
    return render(request, 'shop/courses.html', {'courses': courses})
    # return HttpResponse([str(course) + '<br>' for course in courses])

def single_course(request, course_id):
    # Option 1
    # try:
    #     course = Course.objects.get(pk=course_id)
    #     return render(request, 'single_course.html', {'course': course})
    # except Course.DoesNotExist:
    #     raise Http404("Course does not exist")

    # Option 2
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'shop/single_course.html', {'course': course})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href="{% url "shop:index" %}" class="navbar-brand">Courses shop</a>
        </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

</body>
</html>

templates/shop/courses.html
{% extends 'base.html' %}

{% block title %} All courses {% endblock %}
{% block content %}
<table class="table mt-5 table-bordered table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>title 1</th>
            <th>category 2</th>
            <th>price 3</th>
            <th>students qty 4</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <th><a href="{% url "shop:single_course" course.id %}">{{ course.title }}</a></th>
            <th>{{ course.category }}</th>
            <th>{{ course.price }}</th>
            <th>{{ course.student_qty }}</th>
            <th><button class="btn btn-primary">Buy</button></th>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/shop/single_course.html
{% extends 'base.html' %}
{% block title %}{{ course.title }}{% endblock %}

{% block content %}
    <h1>{{ course.title }}</h1>
    <h2>{{ course.category }}</h2>
    <p>Price: {{ course.price }}</p>
    <p>Students Quantity: {{ course.student_qty }}</p>
    <button class="btn btn-primary">Buy</button>
{% endblock %}